2021-11-15 21:18:39,284 INFO    MainThread:22815 [wandb_setup.py:_flush():71] setting env: {}
2021-11-15 21:18:39,284 INFO    MainThread:22815 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-15 21:18:39,284 INFO    MainThread:22815 [wandb_setup.py:_flush():71] setting login settings: {'api_key': 'a2b321422e079348be6a0858303b4844a0eea6c5'}
2021-11-15 21:18:39,284 INFO    MainThread:22815 [wandb_init.py:_log_setup():357] Logging user logs to /home/wongsiuho561/gpt-j-tuned-for-quotes/wandb/run-20211115_211839-3lp5cqoz/logs/debug.log
2021-11-15 21:18:39,284 INFO    MainThread:22815 [wandb_init.py:_log_setup():358] Logging internal logs to /home/wongsiuho561/gpt-j-tuned-for-quotes/wandb/run-20211115_211839-3lp5cqoz/logs/debug-internal.log
2021-11-15 21:18:39,285 INFO    MainThread:22815 [wandb_init.py:init():390] calling init triggers
2021-11-15 21:18:39,285 INFO    MainThread:22815 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'layers': 28, 'd_model': 4096, 'n_heads': 16, 'n_vocab': 50400, 'norm': 'layernorm', 'pe': 'rotary', 'pe_rotary_dims': 64, 'seq': 2048, 'cores_per_replica': 8, 'per_replica_batch': 1, 'gradient_accumulation_steps': 16, 'warmup_steps': 300, 'anneal_steps': 3000, 'lr': 0.00012, 'end_lr': 1.2e-05, 'weight_decay': 0.1, 'total_steps': 3300, 'tpu_size': 256, 'bucket': 'gptj-base', 'model_dir': 'tuned_to_finbase_3', 'train_set': 'fin.train.index', 'val_set': {}, 'eval_harness_tasks': [], 'val_batches': 622, 'val_every': 300, 'ckpt_every': 300, 'keep_every': 900, 'name': 'tuned_to_finbase_3', 'wandb_project': 'mesh-transformer-jax-3', 'comment': '', 'optimizer': GradientTransformation(init=<function chain.<locals>.init_fn at 0x7f99c3157f70>, update=<function chain.<locals>.update_fn at 0x7f99c3176040>)}
2021-11-15 21:18:39,285 INFO    MainThread:22815 [wandb_init.py:init():435] starting backend
2021-11-15 21:18:39,285 INFO    MainThread:22815 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-15 21:18:39,952 INFO    MainThread:22815 [backend.py:ensure_launched():199] starting backend process...
2021-11-15 21:18:40,614 INFO    MainThread:22815 [backend.py:ensure_launched():204] started backend process with pid: 25561
2021-11-15 21:18:40,616 INFO    MainThread:22815 [wandb_init.py:init():444] backend started and connected
2021-11-15 21:18:40,623 INFO    MainThread:22815 [wandb_init.py:init():503] updated telemetry
2021-11-15 21:18:42,136 INFO    MainThread:22815 [wandb_init.py:init():533] communicating current version
2021-11-15 21:18:42,175 INFO    MainThread:22815 [wandb_init.py:init():538] got version response 
2021-11-15 21:18:42,175 INFO    MainThread:22815 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-15 21:18:42,401 INFO    MainThread:22815 [wandb_init.py:init():576] starting run threads in backend
2021-11-15 21:18:44,255 INFO    MainThread:22815 [wandb_run.py:_console_start():1693] atexit reg
2021-11-15 21:18:44,256 INFO    MainThread:22815 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2021-11-15 21:18:44,257 INFO    MainThread:22815 [wandb_run.py:_redirect():1572] Redirecting console.
2021-11-15 21:18:44,259 INFO    MainThread:22815 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-15 21:18:44,259 INFO    MainThread:22815 [wandb_init.py:init():603] run started, returning control to user process
2021-11-16 05:45:52,595 INFO    MainThread:22815 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-11-16 05:45:52,596 INFO    MainThread:22815 [wandb_run.py:_restore():1635] restore
2021-11-16 05:45:54,605 INFO    MainThread:22815 [wandb_run.py:_restore():1635] restore
2021-11-16 05:45:58,191 ERROR   MainThread:22815 [wandb_run.py:_atexit_cleanup():1681] Problem finishing run
Traceback (most recent call last):
  File "/home/wongsiuho561/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1671, in _atexit_cleanup
    self._on_finish()
  File "/home/wongsiuho561/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1839, in _on_finish
    print("")
OSError: [Errno 5] Input/output error
